### ISSUE TITLE
Update Django to 3.2

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#1098]
The currently used Django version is 2.2 and needs to be migrated to 3.2 (LTS).

**Tasks**

* [x] Follow the guide to [Migrate to Django 3.2](https://docs.djangoproject.com/en/4.0/howto/upgrade-version/)
* [x] Make atomic commits for each chunk of changes (for example: "Updated library X to support Django 3.2", or "Changed import everywhere to use Django 3.2", or "Resolved deprecation issue X in Django 3.2")
* [x] Create a PR that shows that all tests are still succeeding
* [x] Perform visual inspection on the homepage and admin to see if it still looks ok

Known packages to upgrade:

- [x] django-appconf
- [x] django-axes
- [x] django-redis
- [x] django-choices
- [x] drf-extra-fields
- [x] freezegun
- [x] ordered-model
- [x] django-admin-index
- [x] Update django admin overrides stylesheets (see maykin default-project)
- [x] rest_framework_gis

**Comment by ahmadpoorgholam** [comment]
The cims adapter needs to be updated fist
There is an In progress ticket for it now https://github.com/open-zaak/cmis-adapter/issues/63#event-6098151379
