### ISSUE TITLE
Migrate from django-auth-adfs-db to mozilla-django-oidc-db

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#1139]
Looks like django-auth-adfs-db is no longer maintained by isprojects, and we already have the generic mozilla-django-oidc-db library in our dependencies which works with Azure AD/ADFS as well.

This is related to system check `fields.W904` - with the EOL of Django 2.2, we can remove support for django.contrib.postgres.fields.JSONField and instead use django.db.models.JSONField

**Task**

1.7.0 release:

- [x] #1140 
- [x] Remove database table(s) #1142 
- [x] Update documentation #1142 

1.8.0 release:

- [x] Make data migration no-op
- [x] Remove dependency
- [x] Document that upgrade from 1.6.x to 1.8.x directly is not possible, and 1.7.0 needs to be executed if OIDC is relevant. Otherwise manual cleanup is required.
