### ISSUE TITLE
Release 1.7.0 checklist/preparation

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#1183]
- [x] Update translations
- [x] Resolve release blockers
    - [x] https://github.com/VNG-Realisatie/catalogi-api/pull/134
    - [x] https://github.com/VNG-Realisatie/catalogi-api/pull/131
    - [x] https://github.com/VNG-Realisatie/catalogi-api/pull/130
    - [x] #1186
    - [x] Bump Catalogi API version after VNG releases patch version
- [x] Check API specifications for correctness (again)
    - [x] Zaken API
    - [x] Catalogi API
- [x] Bump version to 1.7.0
- [x] Update changelog
- [ ] Tag merge commit
- [ ] Announce release
    - [ ] commonground.nl
    - [ ] Slack
    - [ ] Mailing list
- [ ] Update Helm Chart
