### ISSUE TITLE
As devops, I want to deploy an Appliance to VMware or similar

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#136]
... so I can use my existing infrastructure to run Open Zaak.

**Description**
To accommodate municipalities we will release an Appliance that runs the Docker images.

We can use the work of Bart to get started: https://gitlab.com/delta10/zgw-2

**Tasks**

- [x] Create a script/documentation to (re)create the Appliance
- [x] Create a Virtualbox container: OpenZaak and OpenNotificaties should run with a docker-compose/nginx setup and be accessible.
- [x] Export the Virtualbox container as an Appliance in the OVF v2 format (OVA-file).
- [x] Create documentation to get the Appliance itself up and running in VMware (import, run, and login). A logged in user into the admin of OpenZaak and OpenNotificaties is the end goal.

Until we have hosting capabilities, we don't need to publish this appliance yet.

**Comment by sergei-maertens** [comment]
Split of the Open Notifications aspect in #358, while #350 implements the Open Zaak appliance tooling
