### ISSUE TITLE
As a supplier, I want to use Documenten 1.3 

### ISSUE THREAD

**Issue by annashamray** [open-zaak/open-zaak#1410]
... so I can make use of the latest published standards from VNG.

Now Open Zaak supports Documenten 1.1.0

**Tasks**

* [x] Diff the API spec between Open Zaaks version and the VNG one: https://github.com/VNG-Realisatie/gemma-zaken/blob/master/api-specificatie/drc/1.3.x/openapi.yaml
* [x] Look through Changelog to see any business logic changes: https://github.com/VNG-Realisatie/documenten-api/blob/master/CHANGELOG.rst
* [x] Read the runtime behviour changes: https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/
* [x] Make the code changes 

**Changes in Documenten 1.2**
* [x] added a new claim `documenten.geforceerd-bijwerken` - US #1424
* [x] added a new endpoint `enkelvoudiginformatieobject__zoek` for `EnkelvoudigInformatieObject` resource US #1433
* [x] added a new resource `Verzending` and its related endpoints US #1435
* [x] **(NOT IN CHANGELOG)** added a new property`EnkelvoudigInformatieObject.verschijningsvorm` US #1437 
* [x] changed description of a property `EnkelvoudigInformatieObject.taal` US #1431
* [x] added validation: locked documents cannot be deleted. US #1429

**Changes in Documenten 1.3**
* [x] remove validation: `EnkelvoudigInformatieObject.informatieobject` is not immutable anymore. It can be changed now US #1439
