### ISSUE TITLE
As a supplier, I want to use Catalogi 1.2

### ISSUE THREAD

**Issue by annashamray** [open-zaak/open-zaak#1411]
... so I can make use of the latest published standards from VNG.

Currently Open Zaak supports Catalogi 1.1.1

**Tasks**

* [x] Diff the API spec between Open Zaaks version and the VNG one: https://github.com/VNG-Realisatie/gemma-zaken/blob/master/api-specificatie/ztc/1.2.x/openapi.yaml
* [x] Look through Changelog to see any business logic changes: https://github.com/VNG-Realisatie/catalogi-api/blob/master/CHANGELOG.rst
* [x] Read the runtime behavior changes: https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/
* [x] Create user stories for all changes
* [x] Make the code changes

**Difference between Catalogi 1.2 and Catalogi 1.1**

* [x] Added new claim for update and partial_update endpoints - `catalogi.geforceerd-schrijven`. This is documented as [Correcties](https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/index#correctie) - US #1415
* [x] Added new resource with endpoints `ZaakObjectType` - US #1419 
* [x] New query parameters are added to list endpoints - US #1485:
  - `datumGeldigheid` parameter is added to:
    - `besluittype_list`
    - `informatieobjecttype_list`
    - `eigenschap_list`
    - `resultaattype_list`
    - `roltype_list`
    - `statustype_list`
    - `zaaktype_list`
  - `omschrijving` is added to:
    - `besluittype_list`
    - `informatieobjecttype_list`
  - `zaaktypeIdentificatie`is added to the endpoints:
    - `eigenschap_list`
    - `resultaattype_list`
    - `roltype_list`
    - `statustype_list`
 * [x] **(Not in CHANGELOG)** Added new properties `beginGeldigheid` and `eindeGeldigheid` for resources: US #1420
    - Eigenschap
    - InformatieObjectType
    - ResultaatType
    - RolType
    - StatusType
    - ZaakObjectType (new resource)
 * [x] **(Not in CHANGELOG)** Added new properties `beginObject` and `eindeObject` for resources: US #1420
    - BesluitType
    - Eigenschap
    - InformatieObjectType
    - ZaakType
    - ResultaatType
    - RolType
    - StatusType
    - ZaakObjectType (new resource)
 * [x] **(Not in CHANGELOG)** Added new property `zaaktypeIdentificatie` for resources: US #1423
    - Eigenschap
    - ResultaatType
    - RolType
    - StatusType
    - ZaakTypeInformatieObjectType
 * [x] Added new property `catalogus` for resources: US #1421
    - Eigenschap
    - ResultaatType
    - RolType
    - StatusType
    - ZaakTypeInformatieObjectType
* [x] Add new resource-specific properties: US #1476
    - `BesluitType`:
      - resultaattypen
      - resultaattypenOmschrijving
      - vastgelegdIn
    - `Catalogus`:
      - naam
      - versie
      - begindatumVersie
    - `Eigenschap`:
      - statustype
    - `InformatieObjectType`:
      - besluittypen
      - zaaktypen
      - informatieobjectcategorie
      - trefwoord
      - omschrijvingGeneriek
    - `ZaakType`:
      - verantwoordelijke
      - zaakobjecttypen
      - broncatalogus
      - bronzaaktype
    - `ResultaatType`:
      - procesobjectaard
      - indicatieSpecifiek
      - procestermijn
      - besluittypen
      - besluittypeOmschrijving
      - informatieobjecttypen
      - informatieobjecttypeOmschrijving
    - `StatusType`:
      - doorlooptijd
      - toelichting
      - checklistitemStatustype
      - eigenschappen
      - zaakobjecttype
    - `ZaakTypeInformatieObjectType`:
      - informatieobjecttypeOmschrijving
* [x] Change existing properties:
  - `ResultaatType.omschrijving` max length is changed from 20 to 30 - US #1483
* [x] Change existing validation logic US #1486:
  - **(not in OAS)** Unique constraint of `ZaakType.omschrijving` & `ZaakType.catalogus` is replaced with `ZaakType.identificatie` & `ZaakType.catalogus`

**Comment by annashamray** [comment]
**Inconsistency between OAS and reference implementation**

There is inconsistency between OAS and reference implementation in relation to ZaakType unique constraint. 
According to CHANGELOG of the reference implementation: 

> Change unique constraint of ZaakType.omschrijving & ZaakType.catalogus to ZaakType.identificatie & ZaakType.catalogus (https://github.com/VNG-Realisatie/gemma-zaken/issues/1639);

But in [OAS in gemma_zaken](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/api-specificatie/ztc/1.2.x/openapi.yaml) there is no such change, it sill requires the uniqueness of `ZaakType.omschrijving`: 
```
      operationId: zaaktype_create
      description:
        "Er wordt gevalideerd op:\n- geldigheid `catalogus` URL, dit moet\
        \ een catalogus binnen dezelfde API zijn\n - Uniciteit `catalogus` en `omschrijving`.\
        \ Dezelfde omeschrijving mag enkel  opnieuw gebruikt worden als het zaaktype\
        \ een andere geldigheidsperiode  kent dan bestaande zaaktypen.\n - `deelzaaktypen`\
        \ moeten tot dezelfde catalogus behoren als het ZAAKTYPE."
```

**Comment by joeribekker** [comment]
Make the change as in the changelog

**Comment by joeribekker** [comment]
Reported the inconsistency to VNG: https://github.com/VNG-Realisatie/gemma-zaken/issues/2291

**Comment by annashamray** [comment]
**Inconsistency between OAS and CHANGELOG of the reference implementation related to new date fields**: 

In OAS there is a lot of new date fields for most of the resources:

>   Added new properties `beginGeldigheid `and `eindeGeldigheid` for resources: 
>     * Eigenschap
>     * InformatieObjectType
>     * ResultaatType
>     * RolType
>     * StatusType
> 
> Added new properties `beginObject` and `eindeObject` for resources: 
>     * BesluitType
>     * Eigenschap
>     * InformatieObjectType
>     * ZaakType
>     * ResultaatType
>     * RolType
>     * StatusType
> 

The standard documentation also describes adding new date fields in Catalogi 1.2
But they are not mentioned in the CHANGELOG at all

My guess that this change was forgotten when CHANGELOG was being prepared. 
I plan to include it into Open Zaak
