### ISSUE TITLE
As a supplier, I want to use Besluiten 1.1

### ISSUE THREAD

**Issue by annashamray** [open-zaak/open-zaak#1412]
... so I can make use of the latest published standards from VNG.

Currently Open Zaak supports Besluiten 1.0.1

**Tasks**

* [x] Diff the API spec between Open Zaaks version and the VNG one: https://github.com/VNG-Realisatie/gemma-zaken/blob/master/api-specificatie/brc/1.1.x/openapi.yaml
* [x] Look through Changelog to see any business logic changes: https://github.com/VNG-Realisatie/besluiten-api/blob/master/CHANGELOG.rst
* [x] Read the runtime behavior changes: https://vng-realisatie.github.io/gemma-zaken/standaard/besluiten/
* [x] Make the code changes
    * [x] Support Etag - #1413

**Comment by annashamray** [comment]
The difference between Besluiten 1.1.x and Besluiten 1.0.x:

1. Besluiten 1.1 has ETag support, meaning:
  * GET endpoints support `If-None-Match`  request header which can provide ETag value
  * GET endpoints have ETag response header with calculated ETag value
  * HEAD endpoints are supported with ETag headers

2. In Besluiten 1.1 audittrail endpoints (`/besluiten/{besluit_uuid}/audittrail/{uuid} ` and `/besluiten/{besluit_uuid}/audittrail`) the response includes `RequestId` propery, which doesn't exist in Besluiten 1.0

    Since there is no reference implementation for Besluiten 1.1 it's hard to tell where this property comes from, but I made some investigation. `Audittrail.request_id` was a property which existed in vng_api_common before it was removed in `vng_api_common==1.5.8`. 
    
    The Besluiten reference implementation requires `vng-api-common==1.8.0` so it doesn't have this property. 

    Since it's unknown the source of the property and the reason it's included and it's not described in the standard docs, I will not include it in the Open Zaak for now

**Comment by joeribekker** [comment]
PO-decision: We're leaving out `audittrail.RequestId` even if it appears in Besluiten API 1.1, since its 99% certain a remnant of an old library version.

**Comment by joeribekker** [comment]
To be sure, I made a related issue at VNG: https://github.com/VNG-Realisatie/gemma-zaken/issues/2289
