### ISSUE TITLE
As developer, I want to get rid of Django Choices

### ISSUE THREAD

**Issue by annashamray** [open-zaak/open-zaak#1418]
because the library is not supported anymore

**Description**
The migration manual - https://django-choices.readthedocs.io/en/latest/migrating.html 

**Tasks**

* [ ] update dependencies to versions which don't use django choices lib
* [x] convert all constants from `DjangoChoices` to `models.TextChoices`
* [x] remove `django-choices` from requirements
