### ISSUE TITLE
As a supplier, I want to use Documenten 1.4

### ISSUE THREAD

**Issue by annashamray** [open-zaak/open-zaak#1464]
Previous US to support Documenten 1.3 - https://github.com/open-zaak/open-zaak/issues/1410

**Useful links**
* VNG API specs: https://github.com/VNG-Realisatie/gemma-zaken/blob/master/api-specificatie/drc/
* Changelog: https://github.com/VNG-Realisatie/documenten-api/blob/master/CHANGELOG.rst
* Behaviour changes: https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/

**Changes in Documenten 1.4**
* [x] add `trefwoorden` property to `Enkelvoudiginformatieobject` resource, also add it as query param - US #1545 
* [x] add `expand` query param to `enkelvoudiginformatieobjecten`, `gebruiksrechten`, `verzendingen` endpoints - US #1522
* [x] **[NOT IN OAS]** **BLOCKED** change validation:  remove check `status!='definitief'` from update/patch US #1548 
* [x] change help_text for `verzenddatum` and `ontvangstdatum` properties: add 'DEPRECATED' mark US #1547

**Changes in Documenten 1.4.1** 
* [x] add `lock` field to `BestandsDeel` endpoint - US #1550 

**Changes in Documenten 1.4.2** 
* [x] add `expand query param to enkelvoudiginformatieobjecten `zoek` endpoint - US #1522
* [x] **[NOT IN CHANGELOG]** add other enkelvoudiginformatieobjecten list endpoint params to `zoek` endpoint - US #1525
