### ISSUE TITLE
 As a supplier, I want to use Zaken 1.5

### ISSUE THREAD

**Issue by annashamray** [open-zaak/open-zaak#1465]
Previous US to support Zaken 1.4 - https://github.com/open-zaak/open-zaak/issues/1407

**Useful links**
* VNG API specs: https://github.com/VNG-Realisatie/gemma-zaken/blob/master/api-specificatie/zrc/
* Changelog: https://github.com/VNG-Realisatie/zaken-api/blob/master/CHANGELOG.rst
* Behaviour changes: https://vng-realisatie.github.io/gemma-zaken/standaard/zaken/

**Changes in Zaken 1.5.0**:
* [x] add `expand` query param into zaken list endpoint and show expanded resources in the response - US #1152 

**Changes in Zaken 1.5.1**:
* [x] add `expand` query param into zaken `_zoek` endpoint - US #1152
* [x] remove `resultaattoelichting` from Zaak - US #1543
