### ISSUE TITLE
As a supplier, I want to use Catalogi 1.3

### ISSUE THREAD

**Issue by annashamray** [open-zaak/open-zaak#1466]
Previous US to support Catalogi 1.2 - https://github.com/open-zaak/open-zaak/issues/1411

**Useful links**
* VNG API specs: https://github.com/VNG-Realisatie/gemma-zaken/blob/master/api-specificatie/ztc/
* Changelog: https://github.com/VNG-Realisatie/catalogi-api/blob/master/CHANGELOG.rst
* Behaviour changes: https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/

**Changes in Catalogi 1.3**
* [ ] add new permission scopes `documenten.lezen` and `zaken.lezen` US #1553
* **REMOVED FROM RELEASE** ~~add `datumGeldigheid` query param to `zaaktype_retrieve` endpoint~~ - US #1552 
* [x] **[NOT IN CHANGELOG]** remove `informatieobjecttypeOmschrijving` property from `ZaakTypeInformatieObjectType` resource - US #1555
* [x] **[NOT IN CHANGELOG]** `besluittype.zaaktypen` property is changed to read-only - US #1558 

**Known deviations from Catalogi OAS:**
* In Catalogi 1.3  `StatusType` resource has property `zaakobjecttypen` and `ZaakObjectType` resource has property `statustype`. In Open Zaak implementation `ZaakObjectType` has property `statustype`. This is a target relation between resources. The related acknowledged bug in the standard - https://github.com/VNG-Realisatie/gemma-zaken/issues/2351
* In Catalogi 1.3 `catalogus` property for all Zaaktype subresources is writeable. In OpenZaak it's read-only. This is the target implementation. The related issue - https://github.com/VNG-Realisatie/gemma-zaken/issues/2330
* In Catalogi 1.3 `Statustype.eigenschappen` is writeable, in Open Zaak it's read-only. This is the target implementation. The related issue - https://github.com/VNG-Realisatie/gemma-zaken/issues/2343
