### ISSUE TITLE
As developer, I want to add new properties to catalogi resources

### ISSUE THREAD

**Issue by annashamray** [open-zaak/open-zaak#1476]
It's a part of Catalogi 1.2 support

Master US - https://github.com/open-zaak/open-zaak/issues/1411
Related generic issue in VNG - https://github.com/VNG-Realisatie/gemma-zaken/issues/1847
Issues for specific properties:
* InformatieObjectType.trefwoord - https://github.com/VNG-Realisatie/gemma-zaken/issues/2058
* InformatieObjectType.omschrijvingGeneriek - https://github.com/VNG-Realisatie/gemma-zaken/issues/1847

**Tasks**
- [x] `BesluitType`:
  - [x] resultaattypen
  - [x] resultaattypenOmschrijving
  - [x] vastgelegdIn
- [x] `Catalogus`:
  - [x] naam
  - [x] versie
  - [x] begindatumVersie
- [x] `Eigenschap`:
  -  [x] statustype - explained at https://github.com/VNG-Realisatie/gemma-zaken/issues/2343
- [x] `InformatieObjectType`:
  - [x] besluittypen
  - [x] zaaktypen
  - [x]  informatieobjectcategorie - explained at https://github.com/VNG-Realisatie/gemma-zaken/issues/2344
  - [x] trefwoord
  - [x] omschrijvingGeneriek
- [x] `ZaakType`:
  - [x] verantwoordelijke - explained at https://github.com/VNG-Realisatie/gemma-zaken/issues/2335
  - [x] zaakobjecttypen
  - [x] broncatalogus - explained at https://github.com/VNG-Realisatie/gemma-zaken/issues/2346
  - [x] bronzaaktype - explained at https://github.com/VNG-Realisatie/gemma-zaken/issues/2346
- [x] `ResultaatType`:
  - [x] procesobjectaard
  - [x] indicatieSpecifiek
  - [x] procestermijn
  - [x] besluittypen
  - [x] besluittypeOmschrijving
  - [x] informatieobjecttypen
  - [x] informatieobjecttypeOmschrijving
- [x] `StatusType`:
  - [x] doorlooptijd
  - [x] toelichting
  - [x] checklistitemStatustype
  - [x]  eigenschappen - explained at https://github.com/VNG-Realisatie/gemma-zaken/issues/2343
  - [x]  zaakobjecttype - explained at https://github.com/VNG-Realisatie/gemma-zaken/issues/2334, https://github.com/VNG-Realisatie/gemma-zaken/issues/2351
- [x] `ZaakTypeInformatieObjectType`:
  - [x] informatieobjecttypeOmschrijving

**Implementation details:**
* a lot of relations between zaaktype subresources are created here. For now we add only a basic validation - that they belong to a one catalogus. We don't add validation for related resources in Zaken API, because there is no documentation how it should be done and used

**Comment by joeribekker** [comment]
As per comment, we'll reverse the relation: https://github.com/VNG-Realisatie/gemma-zaken/issues/2351
This way it matches the Information Model
