### ISSUE TITLE
As municipality I want an up-to-date and secure image

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#1502]
..so that I can deploy without worries.

Ref: Amsterdam - Aanpassing Docker

**Tasks**

_Open Zaak_

* [x] Add Trivy to Github Actions. An initial  setup was made here: https://github.com/open-formulieren/open-forms/pull/3129/files.
* [x] Make Trivy report to Github security/dependabot so we can check all issues. Trivy however should never cause failures.
* [x] Remove Vim, and add Nano to the Docker image
* [x] Add apt-get update and upgrade statements to Dockerfile (see also the link in first task)

_Open Notificaties_

* [x] Add Trivy to Github Actions
* [x] Make Trivy report to Github security/dependabot so we can check all issues. Trivy however should never cause failures.
* [x] Remove Vim, and add Nano to the Docker image
* [x] Add apt-get update and upgrade statements to Dockerfile
