### ISSUE TITLE
As developer, I want to know where Open Zaak API's differ from the standard

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#153]
... so I can take this into account when developing.

**Description**
Some issues are mandatory from our point of view but not (yet) added to the standard. This ticket is a placeholder to make an overview of such issues and document them.

- ~#118~ (this was integrated into the standard by VNG)

**Comment by sergei-maertens** [comment]
## Autorisaties API

no differences found

## Besluiten API

- [ ] Description `besluit_create`
- [ ] Description `besluit_update`
- [ ] Description `besluit_partial_update`
- [ ] Schema `Besluit.besluittype` is missing `minLength: 1`

## Catalogi API

## Documenten API

## Zaken API

**Comment by sergei-maertens** [comment]
Created https://github.com/VNG-Realisatie/gemma-zaken/issues/1542 for the leftovers
