### ISSUE TITLE
As municipality, I want to have the ReferentieLijsten API available

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [open-zaak/open-zaak#167]
... so I can use it for the selectielijst.

... so I can use the GemeenteZaak API's independently from an external API for ReferentieLijsten (that probably will not be available in the near future).

**Description**

See https://referentielijsten-api.vng.cloud/api/v1/schema/

**Tasks**

* [x] Fork
* [x] Production grade (read: performance measurements)
* [ ] Add caching
* [x] Hosting setup in k8s (not dedicated)
* [x] See if VNG can host this anyway

No documentation needed. It needs to be up and running "somewhere".

**Comment by Hugo-ter-Doest** [comment]
After discussion with stakeholders we agreed upon adding the ReferentieLijsten API as separate component. And one of the municipalities will host the ReferentieLijsten API for the other participating municipalities.

**Comment by joeribekker** [comment]
We can use this API endpoint for now.

**Comment by joeribekker** [comment]
@Hugo-ter-Doest Can you re-evaluate this issue? We can use the vng.cloud one for now?

**Comment by Hugo-ter-Doest** [comment]
I prefer to use an API endpoint that is hosted by a municipality. I think we cannot depend on VNG Realisatie to host the Referentielijsten API in the long term.

**Comment by sergei-maertens** [comment]
I remember Lazo from Utrecht dropping that they would not mind hosting it.

**Comment by sergei-maertens** [comment]
Discussed:

* Joeri will setup the DNS
* It will be a project forked from reference implementation (but limited to Selectielijst API)
* Publicly available
* Hosted on Utrecht infrastructure (Kubernetes)

After that, we need to update the defaults in Open Zaak to point to that environment and migrate/import the Excel in that environment (I prefer migrating from existing environment so that the same UUIDs are used, which makes data migrations easier)

**Comment by joeribekker** [comment]
Also, document briefly what you did to migrate with the preservation of UUIDs if interesting.

The selectielijst API should already be configurable in Open Zaak as of #225

**Comment by sergei-maertens** [comment]
I'm just going to dump and restore the database... not very exciting imo?

**Comment by joeribekker** [comment]
Like I said: If interesting. Dump and restore is not so interesting.

**Comment by sergei-maertens** [comment]
Available on https://selectielijst.openzaak.nl - currently talking to infrastructure provider on getting the SSL certificate fixed.
