### ISSUE TITLE
Prototype integration for mandates (machtigen)

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#1733]
This is an experiment in the broader context of registering mandate contexts when one entity is acting on behalf of another entity.

Some relevant pointers:

* authentication context data model example, eherkenning bewindvoering (private repo): https://github.com/maykinmedia/authentication-context-schemas/blob/main/testdata/eherkenning-machtigen-kvk-2.json
* research/clarifications posted in the upstream standard: VNG-Realisatie/gemma-zaken#2435

Goals that this experiment must achieve:

1. The details of how an entity was authenticated (which capacity, which level of assurance, which services...) need to be persisted with the case
2. An authorizee must be able to view/manage the cases they started on behalf of another entity
3. An authorizer must be able to view/manage the cases that were started on their behalf
4. If an entity is authenticated in a certain capacity, only cases up to that capacity/authorization may be returned/displayed. This requires adequate filtering mechanisms

The changes as part of this experiment will be tried out and proposed back to the standard via the involved stakeholders (Den Haag, Rotterdam amongst others).

**Tasks**

* [x] Expand `Rol` resources with additional fields
    * `source` that provided the identifying attribute(s) (probably this can be omitted)
    * `level_of_assurance` - indicates how sure we are the authenticated entity is who they claim to be
    * `acting_subject` -> see remark about `MEDEWERKER` below
    * `mandate context`
    * Note that many of these fields have restrictions depending on the value of `betrokkeneType` (there is polymorphism involved)
* [x] Figure out how to deal with KVK Nr. vs RSIN (!) -> use `Vestiging`?
* [x] Document common recipes (eherkenning bewindvoering -> MEDEWERKER doesn't work, since it's someone from the municipality themselves)
* [x] Document (+ test) GET call + filters to retrieve zaken started by an authorizee:
    * Document how to filter on LOA
    * Document how to filter on `indicatieMachtiging`
    * Document how to filter on acting subject (if relevant)
* [x] Ensure everything is properly marked as experimental

**Comment by sergei-maertens** [comment]
Did some digging - RBGZ 2.0 (in development) seems to have vanished off the face of the earth.

I wanted to know if `MEDEWERKER` betrokkene type can be used to put the details of an acting subject (employee of company acts on behalf of person - bewindvoering), but from the docstrings the answer is no (luckily we copied over the definitions from RGBZ into the code):

> Een MEDEWERKER van de organisatie die zaken behandelt uit hoofde van
> zijn of haar functie binnen een ORGANISATORISCHE EENHEID.

So, based on the docstrings I can find there are some betrokkene types that seem to be reserved to the municipality handling the case itself:

* `OrganisatorischeEenheid`
* `Medewerker`

The remainder seem okay to use as "external" entities that are involved with the case: `NatuurlijkPersoon`, `NietNatuurlijkPersoon` and `Vestiging`

**Comment by alextreme** [comment]
![Digid eHerkenning machtigingen drawio](https://github.com/user-attachments/assets/a78b942c-f3a6-4065-a403-9e30683a97b6)
