### ISSUE TITLE
As a municipality I want to export/import catalogues

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [open-zaak/open-zaak#189]
... so I can transfer catalogues from accept to production environment, and share catalogues with other municipalities.

**Description**

- [x] Export Catalog (complete with everything)
- [x] Import Catalog (as a new Catalog)

**Implementation hints**
We're going to use the API serializers to create an export per resource. We'll use a dependency graph between resources to do the import within a single database transaction.

**Tasks**

- [x] Create Django command to: Export resource using the API serializer to a file named after the resource (ie. zaaktypen.json)
- [x] Extend command to: Group all exported JSON files into a ZIP-file.
- [x] Create a dependency graph to read the files in the correct order (ie. 1. catalogi.json, 2. zaaktypen.json, 3 statussen.json, etc.).
- [x] Create Django command to: Import ZIP-file to create all objects.
- [x] Throw error when catalog (the unique field) already exists
- [x] Add export button to Catalog detail Admin UI
- [x] Add import button to Catalog list Admin UI

NOTE: UUIDs are not imported and moved this to another US: #249
NOTE: The import/export of Zaaktypes is moved to a different US: #214

**Comment by sergei-maertens** [comment]
@joeribekker do you want to export the uuid here as well or generate a new one? Exporting them along would result in duplicates across environments, which shouldn't happen, so I'd say that `UUID` must be generated at import time.

**Comment by joeribekker** [comment]
@sergei-maertens good question. I think it should export with uuid.

On import it should ask whether to generate new ones or not. I can imagine that migrating a catalog from one instance to another should not change the uuids. We should indicate when you should say yes or no.

**Comment by joeribekker** [comment]
@sergei-maertens @stevenbal let's discuss at earliest convenience.

**Comment by sergei-maertens** [comment]
yeah we need to discuss, tomorrow/Friday is fine

**Comment by joeribekker** [comment]
Updated original User Story with more details after our discussion.

We decided to use the API to export data, for the following reasons:

- Can be done in a database transaction
- Format adheres to the API format and should port more easily to other suppliers
- No database information is leaked (database agnostic)
