### ISSUE TITLE
As maintainer I want to have a clear indicator of the concept status of a zaaktype as well as a button for publishing 

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [open-zaak/open-zaak#194]
... so I always know what the concept status is.

**Tasks**

- [ ] Remove concept field from the admin everywhere.
- [ ] Add a publish button on the objects detail page (like where delete is also)
- [ ] Add the string "(CONCEPT)" after a Zaaktype's __str__ method if concept=True
