### ISSUE TITLE
AS maintainer of the ZTC I want to have proper version control over my Zaaktypes

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [open-zaak/open-zaak#196]
... so my life will be easier.

We need to introduce a better concept for versions in the admin. To accomplish this should:

**Tasks**

- [ ] Change "versiedatum" to readonly in the admin and set it by default to the "beginDatumGeldigheid" when the object is saved (in the admin).
- [ ] Group versiedatum with begin/eind datum fields.
- [ ] Add a button "Create new version" to create a new version of Zaaktype on the detail page.
- [ ] Throw a validation error if there is no `eindeGeldigheid` filled in.
- [ ] A new version will copy ALL information and related objects to NEW objects (where appropriate, m2ms can ofcourse be the same objects) with the following changes:
   - The concept flag should be true for the new object
   - The `beginGeldigheid` should be set to the `eindeGeldigheid` of the original
  - `eindeGeldigheid` should be set to `None`.
