### ISSUE TITLE
As a municipality I want to export/import zaaktypes

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#214]
... so I can transfer zaaktypes from accept to production environment, and share zaaktypes with other municipalities.

The export of a Zaaktype should include all underlying (Statustype, etc.) AND related objects (BesluitType, InformatieObjectType).

The import is more complex: We need a small step before we can do the actual import:

1. Import all data into a temporary cache/table
2. Show all imported BesluitType and InformatieObjectTypes
3. Next to each BesluitType and InformatieObjectType, show a list of all existing BesluitTypes and existing InformatieObjectType. If you select one, it will not create this object, but uses the existing one. If you select nothing, the object is created.
4. Make all newly created objects have `concept=True`.

**Description**

- [ ] Export (individual) Zaaktype
- [ ] Import Zaaktype (in existing Catalog)
- [ ] Show intermediate screen to link BesluitType en InformatieObjectType to existing objects
- [ ] Perform actual import

**Comment by joeribekker** [comment]
@Hugo-ter-Doest Deze even losgetrokken van #189 want het heeft wat voeten in de aarde. Kan jij aangeven wat de prio van deze is?

**Comment by joeribekker** [comment]
Dit is niet goed automated gegaan. #306 had geen betrekking op dit ticket.
