### ISSUE TITLE
As developer, I want to add the missing archive-actions

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#257]
... so all archive actions actually work.

**Description**
Some archive actions are now missing in the reference implementation. We need to fill these in to make it work.

- [ ] Find out which actions are missing
- [ ] Add missing actions
- [ ] Enable tests for these missing actions in the test suite.

**Comment by sergei-maertens** [comment]
CTRL + F for `raise NotImplementedError`

**Comment by stevenbal** [comment]
PR for documentation of this archiving behavior in standaard https://github.com/VNG-Realisatie/gemma-zaken/pull/1479
