### ISSUE TITLE
As stakeholder, I want to release version 1.0.0 of Open Zaak

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#361]
... so I can offer this version to municipalities.

**Description**
Although technically, not a a real User Story, there are some minor tasks that to be done and/or checked.

* [x] Change version number everywhere (UI, code, etc).
* [x] Tag Open Zaak code
* [x] Release Open Zaak docker
* [x] Release Open Zaak appliance
* [x] Release Open Zaak documentation
* [x] Doublecheck: README, CHANGELOG, LICENSE, CONTRIBUTING, AUTHORS

(add if needed)

* [x] And the same for Open Notifications
