### ISSUE TITLE
As user, I want to have user documentation of Open Zaak

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#364]
... so I can use it easily.

**Description**
We need documentation on how to do things in Open Zaak.

**General topics**

* [x] Login
* [x] Change password
* [x] Password reset
* [x] Admin index
* [x] List and detail views

**Catalogi** ( @stevenbal )
Group required: Catalogi-admin

* [x] Create Catalog
* [x] Create Zaaktype
* [x] Publish Zaaktype
* [x] Create new version of Zaaktype
* [x] Export/Import Catalog
* [x] Export/Import Zaaktype

**User access**
Group required: User-admin

* [x] Groups
* [x] Create new user (and add to group)
* [x] ~~Create new custom group (requires Admin)~~ (docs out of scope)

**API access**
Group required: API-admin

* [x] Create application
* [x] Manage application access

**Comment by sergei-maertens** [comment]
Not done yet
