### ISSUE TITLE
As admin, I want to have default groups in Open Zaak

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#365]
... so I can assign rights based on groups.

**Description**
The following groups need to be created:

* [x] Admin -- Can do everything (including creating custom groups!)
* [x] \<component\> admin -- All access to component
* [x] \<component\> read -- Read only access to component
* [x] User admin -- Can manage users (not groups)
* [x] API admin -- Can manage API access
