### ISSUE TITLE
As sysadmin, I want to know the NLX configuration for Open Zaak

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#375]
... so I can add these configuration parameters to my NLX inway.

**Description**
We need a simple view in OpenZaak that shows the NLX inway configuration along with some documentation on how to connect OpenZaak to NLX. This view can be accessed from the Open Zaak main page.

- [ ] NLX configuration view
- [ ] Documentation where this can be found

**Background**
For now, we decided we are not deploying an NLX inway as part of OpenZaak. This is not our task plus it seems a bit random to do so since as an NLX inway is completely separate from OpenZaak. We also don't have the proper certificate to do this.

**Comment by joeribekker** [comment]
Initial work done here: https://github.com/open-zaak/open-zaak/commits/feature/nlx-config

TODO:

- [ ] Link from admin page somewhere
- [ ] Protect view
- [ ] Make context creation nicer?
