### ISSUE TITLE
As sysadmin, I want to have instructions on how to configure Open Zaak for the first time

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#395]
... so I can start working with after installation.

**Description**
Some documentation needs to be added on "next steps" (a link at the end of each deployment document) to configure Open Zaak for

- [x] Configure Sites.Site
- [ ] Configure basic API-access to eachother (so DRC can talk to ZRC, etc.) -- Maybe we need a button for this, to generate them as well?
- [ ] Configure notifications
- [ ] Create the first API token
- [ ] Make the first API call with this API token

References should be added to the manual for more details, but this document should summerize the first steps basically. Don't just copy text from manual to this doc.
