### ISSUE TITLE
As developer, I want to manage authentication and authorizations in the OpenZaak admin

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#4]
... so I can easily configure them in one place.

**Description**
The Autorisaties API features an interface to manage access to various API's. This needs to be integrated so we can manage at one place both the authentication (client credentials) and authorizations (Autorisaties API UI-like).

![image](https://user-images.githubusercontent.com/96970/69561982-94005f80-0fae-11ea-8727-63d8a7d591bf.png)

**Tasks (see screenshot)**

- [x] Integrate Client credentials within Applicaties.
- [x] Make authorizations read only (preferably with a custom HTML that is more readable)
- [x] Create new admin view to create authorizations and let the "Add new auth..." link open this view in a new page.
- [x] Help the user by adding logic to prevent manual scope/url inputs

**Comment by sergei-maertens** [comment]
As discussed on the phone - the checkboxes reflect the current state :-)
