### ISSUE TITLE
As installer, I want to know what I need before I start the installation of Open Zaak

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#406]
... so I can prepare everything.

**Description**

- [ ] Internal DNS entries: open-zaak.gemeente.local, open-notificaties.gemeente.local
- [ ] Public DNS entry: nlx.gemeente.nl
- [ ] Outgoing Internet connection from the target machine.
