### ISSUE TITLE
As a devops engineer, I want the docker images to be built and published automatically by CI

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#57]
... so I can focus on the infrastructure/code instead of managing builds.

**Description**

Stable releases should be built and pushed by Travis automatically. See for example how [Gemeente Utrecht](https://github.com/GemeenteUtrecht/BInG/commit/0fdf3f997d1151b5ed4a967d8ead58ce020d5166) does this.

- [x] Create a bot user for Docker Hub
- [x] Configure the credentials in Travis environment variables
- [x] Determine a "stable" release strategy
- [x] Script the docker image build

**Comment by sergei-maertens** [comment]
This is already in place :tada:
